### ISSUE TITLE
Can't rebuild

### ISSUE THREAD

**Issue by DeadNumbers** [Clozure/ccl#82]
On Arch Linux x86_64
```
;Building lisp-kernel ...> Error of type SIMPLE-ERROR: Error(s) during kernel compilation.
>                             make: вход в каталог «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
>                             svnversion: E155036: The working copy at '/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664'
>                             is too old (format 10) to work with client version '1.9.7 (r1800392)' (expects format 31). You need to upgrade the working copy first.
>                             
>                             m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../pad.s | as  --64 -o pad.o
>                             m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spjump64.s | as  --64 -o x86-spjump64.o
>                             m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spentry64.s | as  --64 -o x86-spentry64.o
>                             m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-subprims64.s | as  --64 -o x86-subprims64.o
>                             cc -include ../platform-linuxx8664.h -c ../pmcl-kernel.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION="unknown"  -g -O2 -Wno-format -m64 -o pmcl-kernel.o
>                             cc -include ../platform-linuxx8664.h -c ../gc-common.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION="unknown"  -g -O2 -Wno-format -m64 -o gc-common.o
>                             ../pmcl-kernel.c: В функции «ensure_gs_available»:
>                             ../pmcl-kernel.c:1707:3: предупреждение: implicit declaration of function «arch_prctl»; did you mean «__NR_prctl»? [-Wimplicit-function-declaration]
>                                arch_prctl(ARCH_GET_GS, &gs_addr);
>                                ^~~~~~~~~~
>                                __NR_prctl
>                             cc -include ../platform-linuxx8664.h -c ../x86-gc.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION="unknown"  -g -O2 -Wno-format -m64 -o x86-gc.o
>                             In file included from <command-line>:0:0:
>                             ../x86-gc.c: В функции «check_xp»:
>                             ./../platform-linuxx8664.h:32:42: ошибка: dereferencing pointer to incomplete type «ExceptionInformation {aka struct ucontext}»
>                              #define xpGPRvector(x) ((natural *)(&((x)->uc_mcontext.gregs)))
>                                                                       ^
>                             ../x86-gc.c:342:31: замечание: in expansion of macro «xpGPRvector»
>                                natural *regs = (natural *) xpGPRvector(xp);
>                                                            ^~~~~~~~~~~
>                             make: *** [Makefile:46: x86-gc.o] Ошибка 1
>                             make: *** Ожидание завершения заданий…
>                             make: выход из каталога «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
>                             
> While executing: REBUILD-CCL, in process listener(1).

 (660C9689F618) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P T :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x3020002FA39D> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
  (&KEY :CONTEXT :PROCESS :ORIGIN :DETAILED-P :COUNT :START-FRAME-NUMBER :STREAM :PRINT-LEVEL :PRINT-LENGTH :SHOW-INTERNAL-FRAMES :FORMAT)
   CCL::CONTEXT: NIL
   PROCESS: NIL
   CCL::ORIGIN: NIL
   CCL::DETAILED-P: T
   COUNT: 1152921504606846975
   CCL::START-FRAME-NUMBER: 0
   STREAM: #<SYNONYM-STREAM to *TERMINAL-IO* #x3020002FA39D>
   CCL::PRINT-LEVEL: 2
   CCL::PRINT-LENGTH: 5
   CCL::SHOW-INTERNAL-FRAMES: NIL
   FORMAT: :TRADITIONAL

  CCL::FRAME-NUMBER: 0
  *BACKTRACE-PRINT-LEVEL*: 2
  *BACKTRACE-PRINT-LENGTH*: 5
  *BACKTRACE-FORMAT*: :TRADITIONAL
  *STANDARD-OUTPUT*: #<SYNONYM-STREAM to *TERMINAL-IO* #x3020002FA39D>
  *PRINT-CIRCLE*: NIL

 (660C9689F780) : 1 (ABNORMAL-APPLICATION-EXIT) 269
  NIL

  #:G154347: (ERROR)
  CCL::%HANDLERS%: ((ERROR) (PROCESS-RESET))

 (660C9689F7B0) : 2 (BREAK-LOOP-HANDLE-ERROR #<SIMPLE-ERROR #x3020015DCB9D> 14025531408138) 1477
  (CONDITION *TOP-ERROR-FRAME*)
   CONDITION: #<SIMPLE-ERROR #x3020015DCB9D>
   *TOP-ERROR-FRAME*: 14025531408138

  CCL::BOGUS-GLOBALS: NIL
  CCL::NEWVALS: NIL
  CCL::OLDVALS: NIL

 (660C9689F828) : 3 (%ERROR #<SIMPLE-ERROR #x3020015DCB9D> ("make: вход в каталог «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
svnversion: E155036: The working copy at '/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664'
is too old (format 10) to work with client version '1.9.7 (r1800392)' (expects format 31). You need to upgrade the working copy first.

m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../pad.s | as  --64 -o pad.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spjump64.s | as  --64 -o x86-spjump64.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spentry64.s | as  --64 -o x86-spentry64.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-subprims64.s | as  --64 -o x86-subprims64.o
cc -include ../platform-linuxx8664.h -c ../pmcl-kernel.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o pmcl-kernel.o
cc -include ../platform-linuxx8664.h -c ../gc-common.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o gc-common.o
../pmcl-kernel.c: В функции «ensure_gs_available»:
../pmcl-kernel.c:1707:3: предупреждение: implicit declaration of function «arch_prctl»; did you mean «__NR_prctl»? [-Wimplicit-function-declaration]
   arch_prctl(ARCH_GET_GS, &gs_addr);
   ^~~~~~~~~~
   __NR_prctl
cc -include ../platform-linuxx8664.h -c ../x86-gc.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o x86-gc.o
In file included from <command-line>:0:0:
../x86-gc.c: В функции «check_xp»:
./../platform-linuxx8664.h:32:42: ошибка: dereferencing pointer to incomplete type «ExceptionInformation {aka struct ucontext}»
 #define xpGPRvector(x) ((natural *)(&((x)->uc_mcontext.gregs)))
                                          ^
../x86-gc.c:342:31: замечание: in expansion of macro «xpGPRvector»
   natural *regs = (natural *) xpGPRvector(xp);
                               ^~~~~~~~~~~
make: *** [Makefile:46: x86-gc.o] Ошибка 1
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
") 14025531408138) 357
  (CONDITION CCL::ARGS CCL::ERROR-POINTER)
   CONDITION: #<SIMPLE-ERROR #x3020015DCB9D>
   CCL::ARGS: ("make: вход в каталог «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
svnversion: E155036: The working copy at '/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664'
is too old (format 10) to work with client version '1.9.7 (r1800392)' (expects format 31). You need to upgrade the working copy first.

m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../pad.s | as  --64 -o pad.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spjump64.s | as  --64 -o x86-spjump64.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-spentry64.s | as  --64 -o x86-spentry64.o
m4 -DLINUX -DX86 -DX8664 -DHAVE_TLS -I../ ../x86-subprims64.s | as  --64 -o x86-subprims64.o
cc -include ../platform-linuxx8664.h -c ../pmcl-kernel.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o pmcl-kernel.o
cc -include ../platform-linuxx8664.h -c ../gc-common.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o gc-common.o
../pmcl-kernel.c: В функции «ensure_gs_available»:
../pmcl-kernel.c:1707:3: предупреждение: implicit declaration of function «arch_prctl»; did you mean «__NR_prctl»? [-Wimplicit-function-declaration]
   arch_prctl(ARCH_GET_GS, &gs_addr);
   ^~~~~~~~~~
   __NR_prctl
cc -include ../platform-linuxx8664.h -c ../x86-gc.c -DLINUX -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS  -DSVN_REVISION=\"unknown\"  -g -O2 -Wno-format -m64 -o x86-gc.o
In file included from <command-line>:0:0:
../x86-gc.c: В функции «check_xp»:
./../platform-linuxx8664.h:32:42: ошибка: dereferencing pointer to incomplete type «ExceptionInformation {aka struct ucontext}»
 #define xpGPRvector(x) ((natural *)(&((x)->uc_mcontext.gregs)))
                                          ^
../x86-gc.c:342:31: замечание: in expansion of macro «xpGPRvector»
   natural *regs = (natural *) xpGPRvector(xp);
                               ^~~~~~~~~~~
make: *** [Makefile:46: x86-gc.o] Ошибка 1
make: *** Ожидание завершения заданий…
make: выход из каталога «/home/user/Work/Git/ccl/src/ccl/lisp-kernel/linuxx8664»
")
   CCL::ERROR-POINTER: 14025531408138



 (660C9689F850) : 4 (FUNCALL #'#<REBUILD-CCL> :UPDATE NIL :FULL T :CLEAN T :KERNEL T :FORCE NIL :RELOAD T :EXIT NIL :RELOAD-ARGUMENTS NIL :VERBOSE NIL :OPTIONAL-FEATURES NIL :SAVE-SOURCE-LOCATIONS :NO-TEXT :ALLOW-CONSTANT-REDEFINITION T) 2573
  (&KEY :UPDATE :FULL :CLEAN :KERNEL :FORCE :RELOAD :EXIT :RELOAD-ARGUMENTS :VERBOSE :OPTIONAL-FEATURES :SAVE-SOURCE-LOCATIONS :ALLOW-CONSTANT-REDEFINITION)
   CCL::UPDATE: NIL
   CCL::FULL: T
   CCL::CLEAN: T
   CCL::KERNEL: T
   CCL::FORCE: NIL
   CCL::RELOAD: T
   CCL::EXIT: NIL
   CCL::RELOAD-ARGUMENTS: NIL
   CCL::VERBOSE: NIL
   CCL::OPTIONAL-FEATURES: NIL
   CCL::SAVE-SOURCE-LOCATIONS: :NO-TEXT
   CCL::ALLOW-CONSTANT-REDEFINITION: T

  CCL::ALLOW-CONSTANT-REDEFINITION-P: NIL
  CCL::*BUILD-TIME-OPTIONAL-FEATURES*: NIL
  *FEATURES*: (:CLTL2 :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 ...)
  *SAVE-SOURCE-LOCATIONS*: :NO-TEXT
  CCL::CD: #P"/home/user/Work/Git/ccl/src/ccl/"
  CCL::*CERROR-ON-CONSTANT-REDEFINITION*: NIL
  *WARN-IF-REDEFINE-KERNEL*: NIL
  CCL::S: #<STRING-OUTPUT-STREAM  #x3020015DFFDD>
  CCL::PROC: #<EXTERNAL-PROCESS (make -C lisp-kernel/linuxx8664 ...)[8244] (EXITED : 2) #x3020015DFC0D>
  CCL::STATUS: :EXITED
  CCL::EXIT-CODE: 2

 (660C9689FA30) : 5 (CALL-CHECK-REGS REBUILD-CCL :FULL T) 221
  (CCL::FN &REST CCL::ARGS)
   CCL::FN: REBUILD-CCL
   CCL::ARGS: (:FULL T)

  CCL::OLD-REGS: ((REBUILD-CCL :FULL T) #<BASIC-CHARACTER-INPUT-STREAM UTF-8 (PIPE/0) #x3020002FB51D> #<HASH-TABLE :TEST EQ size 4/60 #x3020002FC45D> NIL)

 (660C9689FA68) : 6 (TOPLEVEL-EVAL (REBUILD-CCL :FULL T) NIL) 701
  (CCL::FORM &OPTIONAL CCL::ENV)
   CCL::FORM: (REBUILD-CCL :FULL T)
   CCL::ENV: NIL

  #:WHOLE154284: (NIL)
  #:ARGS154285: NIL
  CCL::VARS: NIL
  PACKAGE: #<Package "COMMON-LISP-USER">

 (660C9689FAF8) : 7 (READ-LOOP :INPUT-STREAM #<BASIC-CHARACTER-INPUT-STREAM UTF-8 (PIPE/0) #x3020002FB51D> :OUTPUT-STREAM #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (TTY/1) #x3020002FB08D> :BREAK-LEVEL 0 :PROMPT-FUNCTION #<Compiled-function (:INTERNAL CCL::READ-LOOP) (Non-Global)  #x300000536D8F>) 2317
  (&KEY :INPUT-STREAM :OUTPUT-STREAM :BREAK-LEVEL :PROMPT-FUNCTION)
   INPUT-STREAM: #<BASIC-CHARACTER-INPUT-STREAM UTF-8 (PIPE/0) #x3020002FB51D>
   OUTPUT-STREAM: #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (TTY/1) #x3020002FB08D>
   CCL::BREAK-LEVEL: 0
   CCL::PROMPT-FUNCTION: #<Compiled-function (:INTERNAL CCL::READ-LOOP) (Non-Global)  #x300000536D8F>

  CCL::*BREAK-LEVEL*: 0
  CCL::*LAST-BREAK-LEVEL*: 0
  *LOADING-FILE-SOURCE-FILE*: NIL
  CCL::*LOADING-TOPLEVEL-LOCATION*: #<SOURCE-NOTE Interactive "(ccl:rebuild-ccl :full t)">
  CCL::*IN-READ-LOOP*: NIL
  ***: NIL
  **: NIL
  *: NIL
  +++: NIL
  ++: NIL
  +: NIL
  ///: NIL
  //: NIL
  /: NIL
  -: (REBUILD-CCL :FULL T)
  CCL::EOF-VALUE: (NIL)
  CCL::EOF-COUNT: 0
  CCL::*SHOW-AVAILABLE-RESTARTS*: NIL
  MAP: #<HASH-TABLE :TEST EQ size 4/60 #x3020002FC45D>
  #:ABORT-BREAK: #<RESTART ABORT-BREAK #x660CB79F253D>
  #:ABORT: #<RESTART ABORT #x660CB79F24ED>
  #:G154236: (#<RESTART ABORT #x660CB79F24ED> #<RESTART ABORT-BREAK #x660CB79F253D>)
  CCL::%RESTARTS%: ((#<# # #x660CB79F24ED> #<# # #x660CB79F253D>) (#<# # #x660CB79F27DD> #<# # #x660CB79F282D>))
  CCL::FORM: (REBUILD-CCL :FULL T)
  CCL::ENV: NIL
  CCL::PRINT-RESULT: T
  CCL::*NX-SOURCE-NOTE-MAP*: #<HASH-TABLE :TEST EQ size 4/60 #x3020002FC45D>

 (660C9689FD58) : 8 (RUN-READ-LOOP :BREAK-LEVEL 0) 157
  (&REST CCL::ARGS)
   CCL::ARGS: (:BREAK-LEVEL 0)



 (660C9689FD80) : 9 (TOPLEVEL-LOOP) 101
  NIL



 (660C9689FDA8) : 10 (FUNCALL #'#<(:INTERNAL (TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T)))>) 101
  NIL

  CCL::F: CCL::LISTENER-FUNCTION
  CCL::INIT-FILE: ("home:ccl-init" "home:\\.ccl-init")

 (660C9689FDC8) : 11 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
  NIL

  *TERMINAL-IO*: #<ECHOING-TWO-WAY-STREAM input #<BASIC-CHARACTER-INPUT-STREAM UTF-8 (PIPE/0) #x3020002FB51D>, output #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (TTY/1) #x3020002FB08D> #x3020002FCE4D>
  CCL::CLOSE-STREAMS: NIL
  CCL::CLEANUP-FUNCTION: #<COMPILED-LEXICAL-CLOSURE (:INTERNAL #) #x3020002F977F>
  CCL::INITIAL-FUNCTION: #<COMPILED-LEXICAL-CLOSURE (:INTERNAL #) #x3020002F972F>
  CCL::AUTO-FLUSH: T
  OUTPUT-STREAM: #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (TTY/1) #x3020002FB08D>
  INPUT-STREAM: #<BASIC-CHARACTER-INPUT-STREAM UTF-8 (PIPE/0) #x3020002FB51D>
  CCL::ECHOING: T

 (660C9689FE60) : 12 (RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x3020002F927D> (#<COMPILED-LEXICAL-CLOSURE # #x3020002F8DAF>)) 709
  (PROCESS CCL::INITIAL-FORM)
   PROCESS: #<TTY-LISTENER listener(1) [Active] #x3020002F927D>
   CCL::INITIAL-FORM: (#<COMPILED-LEXICAL-CLOSURE # #x3020002F8DAF>)

  CCL::EXITED: NIL
  #:G156239: (PROCESS-RESET)
  CCL::%HANDLERS%: ((PROCESS-RESET))
  #:ABORT: #<RESTART ABORT #x660CB79F282D>
  #:ABORT-BREAK: #<RESTART ABORT-BREAK #x660CB79F27DD>
  #:G156240: (#<RESTART ABORT-BREAK #x660CB79F27DD> #<RESTART ABORT #x660CB79F282D>)
  CCL::%RESTARTS%: ((#<# # #x660CB79F27DD> #<# # #x660CB79F282D>))

 (660C9689FEF0) : 13 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<TTY-LISTENER listener(1) [Active] #x3020002F927D> (#<COMPILED-LEXICAL-CLOSURE # #x3020002F8DAF>)) 573
  (PROCESS CCL::INITIAL-FORM)
   PROCESS: #<TTY-LISTENER listener(1) [Active] #x3020002F927D>
   CCL::INITIAL-FORM: (#<COMPILED-LEXICAL-CLOSURE # #x3020002F8DAF>)

  *CURRENT-PROCESS*: #<TTY-LISTENER listener(1) [Active] #x3020002F927D>
  #:G156225: (*PRINT-PPRINT-DISPATCH* CCL::*FREE-XPS* CCL::*FREE-CIRCULARITY-HASH-TABLES* CCL::*LOGICAL-BLOCK-XP* CCL::*FORMAT-TOP-LEVEL* ...)
  #:G156226: (#<PPRINT-DISPATCH-TABLE #x3020002FD63D> NIL NIL NIL NIL ...)
  CCL::*INTERRUPT-LEVEL*: 0
  #:G156227: ("Active")
  #:G156228: "Reset"

 (660C9689FF98) : 14 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277
  NIL

  CCL::*CURRENT-LISP-THREAD*: #<LISP-THREAD listener [tcr @ #x660C96B04570] #x3020002F8E8D>
  CCL::INITIAL-FUNCTION: (#<Compiled-function # (Non-Global)  #x3000004AB4EF> #<TTY-LISTENER listener(1) [Active] #x3020002F927D> (#))
  CCL::TCR: 14025531721902
  CCL::THREAD: #<LISP-THREAD listener [tcr @ #x660C96B04570] #x3020002F8E8D>

Version 1.11-r16635  (LinuxX8664)
```

**Comment by xrme** [comment]
This looks like https://github.com/Clozure/ccl/pull/80

Those changes need to be brought into the 1.11 branch.
