### ISSUE TITLE
lisp kernel doesn't build on ubuntu 17.10

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#76]
```
../x86-gc.c: In function ‘check_xp’:
./../platform-linuxx8664.h:31:42: error: dereferencing pointer to incomplete type ‘ExceptionInformation {aka struct ucontext}’
 #define xpGPRvector(x) ((natural *)(&((x)->uc_mcontext.gregs)))
                                          ^
../x86-gc.c:341:31: note: in expansion of macro ‘xpGPRvector’
   natural *regs = (natural *) xpGPRvector(xp);
                               ^~~~~~~~~~~
```

The glibc people decided that it was bad namespace hygiene to have `ucontext_t` be a typedef for `struct ucontext`. They changed it to `struct ucontext_t`.

See https://github.com/voidlinux/void-packages/issues/7284 and https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27struct_ucontext.27

We'll have to see if we can use the `ucontext_t` typedef everywhere and still build on older systems.

**Comment by xrme** [comment]
The lisp kernel builds on Ubuntu 17.10 now.

This should be ported to the 1.11 branch.
